/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ClinicRegistrationRouteImport } from './routes/clinic-registration'
import { Route as ClinicPortalRouteImport } from './routes/clinic-portal'
import { Route as ClinicLoginRouteImport } from './routes/clinic-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicPortalIndexRouteImport } from './routes/clinic-portal/index'
import { Route as ClinicsSlugRouteImport } from './routes/clinics.$slug'
import { Route as ClinicPortalManageRouteImport } from './routes/clinic-portal/manage'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminProceduresRouteImport } from './routes/admin/procedures'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminClinicsRouteImport } from './routes/admin/clinics'
import { Route as AdminClinicRequestsRouteImport } from './routes/admin/clinic-requests'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AccountProfileRouteImport } from './routes/account/profile'
import { Route as AccountBookingsRouteImport } from './routes/account/bookings'
import { Route as AdminClinicsIndexRouteImport } from './routes/admin/clinics/index'
import { Route as AdminClinicsNewRouteImport } from './routes/admin/clinics/new'
import { Route as AdminClinicsIdRouteImport } from './routes/admin/clinics/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRegistrationRoute = ClinicRegistrationRouteImport.update({
  id: '/clinic-registration',
  path: '/clinic-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicPortalRoute = ClinicPortalRouteImport.update({
  id: '/clinic-portal',
  path: '/clinic-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicLoginRoute = ClinicLoginRouteImport.update({
  id: '/clinic-login',
  path: '/clinic-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicPortalIndexRoute = ClinicPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicPortalRoute,
} as any)
const ClinicsSlugRoute = ClinicsSlugRouteImport.update({
  id: '/clinics/$slug',
  path: '/clinics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicPortalManageRoute = ClinicPortalManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ClinicPortalRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProceduresRoute = AdminProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicRequestsRoute = AdminClinicRequestsRouteImport.update({
  id: '/clinic-requests',
  path: '/clinic-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBookingsRoute = AccountBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AccountRoute,
} as any)
const AdminClinicsIndexRoute = AdminClinicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminClinicsRoute,
} as any)
const AdminClinicsNewRoute = AdminClinicsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminClinicsRoute,
} as any)
const AdminClinicsIdRoute = AdminClinicsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminClinicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/clinic-login': typeof ClinicLoginRoute
  '/clinic-portal': typeof ClinicPortalRouteWithChildren
  '/clinic-registration': typeof ClinicRegistrationRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clinic-requests': typeof AdminClinicRequestsRoute
  '/admin/clinics': typeof AdminClinicsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/clinic-portal/manage': typeof ClinicPortalManageRoute
  '/clinics/$slug': typeof ClinicsSlugRoute
  '/clinic-portal/': typeof ClinicPortalIndexRoute
  '/admin/clinics/$id': typeof AdminClinicsIdRoute
  '/admin/clinics/new': typeof AdminClinicsNewRoute
  '/admin/clinics/': typeof AdminClinicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/clinic-login': typeof ClinicLoginRoute
  '/clinic-registration': typeof ClinicRegistrationRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clinic-requests': typeof AdminClinicRequestsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/clinic-portal/manage': typeof ClinicPortalManageRoute
  '/clinics/$slug': typeof ClinicsSlugRoute
  '/clinic-portal': typeof ClinicPortalIndexRoute
  '/admin/clinics/$id': typeof AdminClinicsIdRoute
  '/admin/clinics/new': typeof AdminClinicsNewRoute
  '/admin/clinics': typeof AdminClinicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/clinic-login': typeof ClinicLoginRoute
  '/clinic-portal': typeof ClinicPortalRouteWithChildren
  '/clinic-registration': typeof ClinicRegistrationRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/account/bookings': typeof AccountBookingsRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/clinic-requests': typeof AdminClinicRequestsRoute
  '/admin/clinics': typeof AdminClinicsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/procedures': typeof AdminProceduresRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/clinic-portal/manage': typeof ClinicPortalManageRoute
  '/clinics/$slug': typeof ClinicsSlugRoute
  '/clinic-portal/': typeof ClinicPortalIndexRoute
  '/admin/clinics/$id': typeof AdminClinicsIdRoute
  '/admin/clinics/new': typeof AdminClinicsNewRoute
  '/admin/clinics/': typeof AdminClinicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/clinic-login'
    | '/clinic-portal'
    | '/clinic-registration'
    | '/compare'
    | '/favorites'
    | '/login'
    | '/register'
    | '/account/bookings'
    | '/account/profile'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/clinic-requests'
    | '/admin/clinics'
    | '/admin/dashboard'
    | '/admin/procedures'
    | '/admin/reviews'
    | '/clinic-portal/manage'
    | '/clinics/$slug'
    | '/clinic-portal/'
    | '/admin/clinics/$id'
    | '/admin/clinics/new'
    | '/admin/clinics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/clinic-login'
    | '/clinic-registration'
    | '/compare'
    | '/favorites'
    | '/login'
    | '/register'
    | '/account/bookings'
    | '/account/profile'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/clinic-requests'
    | '/admin/dashboard'
    | '/admin/procedures'
    | '/admin/reviews'
    | '/clinic-portal/manage'
    | '/clinics/$slug'
    | '/clinic-portal'
    | '/admin/clinics/$id'
    | '/admin/clinics/new'
    | '/admin/clinics'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/clinic-login'
    | '/clinic-portal'
    | '/clinic-registration'
    | '/compare'
    | '/favorites'
    | '/login'
    | '/register'
    | '/account/bookings'
    | '/account/profile'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/clinic-requests'
    | '/admin/clinics'
    | '/admin/dashboard'
    | '/admin/procedures'
    | '/admin/reviews'
    | '/clinic-portal/manage'
    | '/clinics/$slug'
    | '/clinic-portal/'
    | '/admin/clinics/$id'
    | '/admin/clinics/new'
    | '/admin/clinics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ClinicLoginRoute: typeof ClinicLoginRoute
  ClinicPortalRoute: typeof ClinicPortalRouteWithChildren
  ClinicRegistrationRoute: typeof ClinicRegistrationRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ClinicsSlugRoute: typeof ClinicsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-registration': {
      id: '/clinic-registration'
      path: '/clinic-registration'
      fullPath: '/clinic-registration'
      preLoaderRoute: typeof ClinicRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-portal': {
      id: '/clinic-portal'
      path: '/clinic-portal'
      fullPath: '/clinic-portal'
      preLoaderRoute: typeof ClinicPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-login': {
      id: '/clinic-login'
      path: '/clinic-login'
      fullPath: '/clinic-login'
      preLoaderRoute: typeof ClinicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-portal/': {
      id: '/clinic-portal/'
      path: '/'
      fullPath: '/clinic-portal/'
      preLoaderRoute: typeof ClinicPortalIndexRouteImport
      parentRoute: typeof ClinicPortalRoute
    }
    '/clinics/$slug': {
      id: '/clinics/$slug'
      path: '/clinics/$slug'
      fullPath: '/clinics/$slug'
      preLoaderRoute: typeof ClinicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic-portal/manage': {
      id: '/clinic-portal/manage'
      path: '/manage'
      fullPath: '/clinic-portal/manage'
      preLoaderRoute: typeof ClinicPortalManageRouteImport
      parentRoute: typeof ClinicPortalRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procedures': {
      id: '/admin/procedures'
      path: '/procedures'
      fullPath: '/admin/procedures'
      preLoaderRoute: typeof AdminProceduresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinic-requests': {
      id: '/admin/clinic-requests'
      path: '/clinic-requests'
      fullPath: '/admin/clinic-requests'
      preLoaderRoute: typeof AdminClinicRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/bookings': {
      id: '/account/bookings'
      path: '/bookings'
      fullPath: '/account/bookings'
      preLoaderRoute: typeof AccountBookingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/clinics/': {
      id: '/admin/clinics/'
      path: '/'
      fullPath: '/admin/clinics/'
      preLoaderRoute: typeof AdminClinicsIndexRouteImport
      parentRoute: typeof AdminClinicsRoute
    }
    '/admin/clinics/new': {
      id: '/admin/clinics/new'
      path: '/new'
      fullPath: '/admin/clinics/new'
      preLoaderRoute: typeof AdminClinicsNewRouteImport
      parentRoute: typeof AdminClinicsRoute
    }
    '/admin/clinics/$id': {
      id: '/admin/clinics/$id'
      path: '/$id'
      fullPath: '/admin/clinics/$id'
      preLoaderRoute: typeof AdminClinicsIdRouteImport
      parentRoute: typeof AdminClinicsRoute
    }
  }
}

interface AccountRouteChildren {
  AccountBookingsRoute: typeof AccountBookingsRoute
  AccountProfileRoute: typeof AccountProfileRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountBookingsRoute: AccountBookingsRoute,
  AccountProfileRoute: AccountProfileRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminClinicsRouteChildren {
  AdminClinicsIdRoute: typeof AdminClinicsIdRoute
  AdminClinicsNewRoute: typeof AdminClinicsNewRoute
  AdminClinicsIndexRoute: typeof AdminClinicsIndexRoute
}

const AdminClinicsRouteChildren: AdminClinicsRouteChildren = {
  AdminClinicsIdRoute: AdminClinicsIdRoute,
  AdminClinicsNewRoute: AdminClinicsNewRoute,
  AdminClinicsIndexRoute: AdminClinicsIndexRoute,
}

const AdminClinicsRouteWithChildren = AdminClinicsRoute._addFileChildren(
  AdminClinicsRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminClinicRequestsRoute: typeof AdminClinicRequestsRoute
  AdminClinicsRoute: typeof AdminClinicsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProceduresRoute: typeof AdminProceduresRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminClinicRequestsRoute: AdminClinicRequestsRoute,
  AdminClinicsRoute: AdminClinicsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProceduresRoute: AdminProceduresRoute,
  AdminReviewsRoute: AdminReviewsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClinicPortalRouteChildren {
  ClinicPortalManageRoute: typeof ClinicPortalManageRoute
  ClinicPortalIndexRoute: typeof ClinicPortalIndexRoute
}

const ClinicPortalRouteChildren: ClinicPortalRouteChildren = {
  ClinicPortalManageRoute: ClinicPortalManageRoute,
  ClinicPortalIndexRoute: ClinicPortalIndexRoute,
}

const ClinicPortalRouteWithChildren = ClinicPortalRoute._addFileChildren(
  ClinicPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ClinicLoginRoute: ClinicLoginRoute,
  ClinicPortalRoute: ClinicPortalRouteWithChildren,
  ClinicRegistrationRoute: ClinicRegistrationRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ClinicsSlugRoute: ClinicsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
